In [5]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
foo = np.tile(np.array([[0,0,1],[1,0,0]]), (4,4))
print foo

[[0 0 1 0 0 1 0 0 1 0 0 1]
 [1 0 0 1 0 0 1 0 0 1 0 0]
 [0 0 1 0 0 1 0 0 1 0 0 1]
 [1 0 0 1 0 0 1 0 0 1 0 0]
 [0 0 1 0 0 1 0 0 1 0 0 1]
 [1 0 0 1 0 0 1 0 0 1 0 0]
 [0 0 1 0 0 1 0 0 1 0 0 1]
 [1 0 0 1 0 0 1 0 0 1 0 0]]


In [10]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

In [11]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


In [12]:
# Given a 1D array, negate all elements which are between 3 and 8, in place
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [17]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [18]:
A = np.array([[1,2,3]])
print A.shape
B = np.transpose(np.array([[1,1,1]]))
print B.shape
print np.multiply(A, B) # broadcasting
print np.dot(A, B)

(1, 3)
(3, 1)
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[6]]


In [22]:
Z = np.random.uniform(0,10,10)
print Z
print Z.dtype
print (np.trunc(Z))

[ 9.6179597   9.10756306  8.95336625  4.39078836  6.19034821  0.46847649
  6.75293295  5.22386423  5.62167311  3.06043981]
float64
[ 9.  9.  8.  4.  6.  0.  6.  5.  5.  3.]


In [23]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [27]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)
print(Z.dtype)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
float64


In [28]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


In [31]:
Z = np.random.random(10)
# Z.sort()    # save to Z
print sorted(Z)  # ref only, no change to Z
print(Z)

[0.015172952604047052, 0.12982298574539031, 0.20366094672517421, 0.22416420159448058, 0.49346861739436998, 0.52003489370824851, 0.54528777665036565, 0.72675521804666332, 0.90409320762651535, 0.97753209888044956]
[ 0.12982299  0.20366095  0.49346862  0.9775321   0.90409321  0.01517295
  0.2241642   0.54528778  0.72675522  0.52003489]


In [34]:
# sum a small array faster than np.sum
print np.add.reduce(np.arange(10))
print np.multiply.reduce(np.arange(10))

45
0
